export const SELL_REQUEST="PRODUCT_REQUEST"
export const SELL_POST_SUCCESS="PRODUCT_GET_SUCCESS"
export const SELL_FAILUER="PRODUCT_FAILUER"  

export const SELL_GET_SUCCESS = "SELL_GET_SUCCESS";
export const SELL_EDIT_SUCCESS = "SELL_EDIT_SUCCESS";
export const SELL_DELETE_SUCCESS = "SELL_DELETE_SUCCESS";

export const COUNT="COUNT"
export const BUY_GET_SUCCESS="BUY_GET_SUCCESS"


